options = optimoptions(@fmincon,'Algorithm','interior-point',... 
    'Display','off','SpecifyObjectiveGradient',true,'SpecifyConstraintGradient',true,...  
    'HessianFcn',@hessinterior);

[x,fval,mflag,output] = fmincon(@bigtoleft,[-1,-1,-1],...   
                    [],[],[],[],[],[],@twocone,options);
