function [tnodes,telements] = CreateGeometry()
holes = false; 
t = linspace(pi/30,2*pi,30);

if holes
    cxcoord = {sin(t), ...
               +0.2 + 0.1*cos(t),  ...
               -0.2 + 0.1*sin(t),  ...
               -0.2 + 0.1*sin(t),  ...
               +0.2 + 0.1*sin(t),  ...
               0.1*sin(t)};
           
    cycoord = {cos(t), ...
               +0.2 + 0.1*sin(t),   ...
               -0.2 + 0.1*cos(t),   ...
               +0.2 + 0.1*cos(t),   ...
               -0.2 + 0.1*cos(t),   ...
               0.1*cos(t)};

    pgon = polyshape(cxcoord,cycoord);   
else
    t = linspace(0,2*pi/4,30);
    pgon = polyshape({[0.5*sin(t) 0]},{[0.5*cos(t) 0]});
end           
tr = triangulation(pgon);
%
tnodes = tr.Points';
telements = tr.ConnectivityList';

end

