%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialization routine
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

default_tolerance = 10^(-8); % Default tolerance CG method

cas_test=cell(0);

cas_test{(end+1)} = struct('nom', 'Controllability fractional heat eq. s=0.5',...
		     'nbeq', 1,...
		     'nbc', 1,...
             'T', 0.5,...,
             'param_s', 0.5,...
             'mat_B', @(x) intervalle(x,-0.3,0.8),...
             'y0', @(x) sin(pi.*x),...
             'maillage','uniforme',...
             'phi', 'h^4',... %penalization parameter
             'methode', 'euler');
         
cas_test{(end+1)} = struct('nom', 'Controllability fractional heat eq. s=0.8',...
		     'nbeq', 1,...
		     'nbc', 1,...
             'T', 0.5,...,
             'param_s', 0.8,...
             'mat_B', @(x) intervalle(x,-0.3,0.5),...
             'y0', @(x) sin(pi.*x),...
             'maillage','uniforme',...
             'phi', 'h^4',... %penalization parameter
             'methode', 'euler');
         
fh=localfunctions;

function [y]=intervalle(x,a,b)
    y=(x>=a).*(x<=b);
end

